# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=b'images')),
                ('rating', models.CharField(max_length=50)),
                ('prep_time', models.CharField(max_length=50)),
                ('cooking_time', models.CharField(max_length=50)),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('cooking_instructions', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2017, 8, 4, 8, 56, 49, 580738))),
            ],
        ),
    ]
