# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to=b'images')),
                ('rating', models.IntegerField()),
                ('prep_time', models.CharField(max_length=50)),
                ('cooking_time', models.CharField(max_length=50)),
                ('servings', models.IntegerField()),
                ('ingredients', models.TextField()),
                ('cooking_instructions', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
