# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-04 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 9, 0, 15, 383223)),
        ),
    ]
