# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 07:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20170804_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='rating',
        ),
    ]
