# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('star_ratings', '0003_auto_20160721_1127'),
        ('recipe_app', '0004_remove_recipes_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='rating',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='star_ratings.Rating'),
        ),
    ]
