# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_recipes_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='rating',
            field=models.CharField(max_length=50),
        ),
    ]
